import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gradient-to-r from-blue-50 to-blue-100`}
      >
       <header className="bg-blue-500 py-4 shadow-lg">
          <div className="container mx-auto text-center">
          <h1 className="text-white text-2xl font-bold font-serif">Plataforma de Apoio TEA</h1>
            <main className="container mx-auto px-4 py-8">{children}</main>
            <footer className="bg-blue-500 py-4 mt-10">
          <div className="container mx-auto text-center">
            <p className="text-white">© 2024 Plataforma de Apoio a Autistas</p>
            </div>
            </footer>
          </div>
        </header>
      </body>
    </html>
  );
}
